lib: [
  "_build/install/default/lib/Cobb/META"
  "_build/install/default/lib/Cobb/context/context.a" {"context/context.a"}
  "_build/install/default/lib/Cobb/context/context.cma" {"context/context.cma"}
  "_build/install/default/lib/Cobb/context/context.cmi" {"context/context.cmi"}
  "_build/install/default/lib/Cobb/context/context.cmt" {"context/context.cmt"}
  "_build/install/default/lib/Cobb/context/context.cmx" {"context/context.cmx"}
  "_build/install/default/lib/Cobb/context/context.cmxa" {"context/context.cmxa"}
  "_build/install/default/lib/Cobb/context/context.ml" {"context/context.ml"}
  "_build/install/default/lib/Cobb/dune-package"
  "_build/install/default/lib/Cobb/opam"
  "_build/install/default/lib/Cobb/pieces/pieces.a" {"pieces/pieces.a"}
  "_build/install/default/lib/Cobb/pieces/pieces.cma" {"pieces/pieces.cma"}
  "_build/install/default/lib/Cobb/pieces/pieces.cmi" {"pieces/pieces.cmi"}
  "_build/install/default/lib/Cobb/pieces/pieces.cmt" {"pieces/pieces.cmt"}
  "_build/install/default/lib/Cobb/pieces/pieces.cmx" {"pieces/pieces.cmx"}
  "_build/install/default/lib/Cobb/pieces/pieces.cmxa" {"pieces/pieces.cmxa"}
  "_build/install/default/lib/Cobb/pieces/pieces.ml" {"pieces/pieces.ml"}
  "_build/install/default/lib/Cobb/postprocess/postprocess.a" {"postprocess/postprocess.a"}
  "_build/install/default/lib/Cobb/postprocess/postprocess.cma" {"postprocess/postprocess.cma"}
  "_build/install/default/lib/Cobb/postprocess/postprocess.cmi" {"postprocess/postprocess.cmi"}
  "_build/install/default/lib/Cobb/postprocess/postprocess.cmt" {"postprocess/postprocess.cmt"}
  "_build/install/default/lib/Cobb/postprocess/postprocess.cmx" {"postprocess/postprocess.cmx"}
  "_build/install/default/lib/Cobb/postprocess/postprocess.cmxa" {"postprocess/postprocess.cmxa"}
  "_build/install/default/lib/Cobb/postprocess/postprocess.ml" {"postprocess/postprocess.ml"}
  "_build/install/default/lib/Cobb/tracking/tracking.a" {"tracking/tracking.a"}
  "_build/install/default/lib/Cobb/tracking/tracking.cma" {"tracking/tracking.cma"}
  "_build/install/default/lib/Cobb/tracking/tracking.cmi" {"tracking/tracking.cmi"}
  "_build/install/default/lib/Cobb/tracking/tracking.cmt" {"tracking/tracking.cmt"}
  "_build/install/default/lib/Cobb/tracking/tracking.cmx" {"tracking/tracking.cmx"}
  "_build/install/default/lib/Cobb/tracking/tracking.cmxa" {"tracking/tracking.cmxa"}
  "_build/install/default/lib/Cobb/tracking/tracking.ml" {"tracking/tracking.ml"}
  "_build/install/default/lib/Cobb/utils/utils.a" {"utils/utils.a"}
  "_build/install/default/lib/Cobb/utils/utils.cma" {"utils/utils.cma"}
  "_build/install/default/lib/Cobb/utils/utils.cmi" {"utils/utils.cmi"}
  "_build/install/default/lib/Cobb/utils/utils.cmt" {"utils/utils.cmt"}
  "_build/install/default/lib/Cobb/utils/utils.cmx" {"utils/utils.cmx"}
  "_build/install/default/lib/Cobb/utils/utils.cmxa" {"utils/utils.cmxa"}
  "_build/install/default/lib/Cobb/utils/utils.ml" {"utils/utils.ml"}
]
libexec: [
  "_build/install/default/lib/Cobb/context/context.cmxs" {"context/context.cmxs"}
  "_build/install/default/lib/Cobb/pieces/pieces.cmxs" {"pieces/pieces.cmxs"}
  "_build/install/default/lib/Cobb/postprocess/postprocess.cmxs" {"postprocess/postprocess.cmxs"}
  "_build/install/default/lib/Cobb/tracking/tracking.cmxs" {"tracking/tracking.cmxs"}
  "_build/install/default/lib/Cobb/utils/utils.cmxs" {"utils/utils.cmxs"}
]
bin: [
  "_build/install/default/bin/Cobb"
]
doc: [
  "_build/install/default/doc/Cobb/README.md"
]
